version: '3'

services:
  bluesky:
    container_name: bluesky
    image: turinginst/bluesky:1.4.0-dev
    expose:
      - 9000
      - 9001
  bluebird:
    container_name: bluebird
    depends_on:
      - bluesky
    image: turinginst/bluebird:latest
    ports:
      - 5001:5001
    environment:
      - BS_HOST=bluesky
  web:
    container_name: twitcher
    depends_on:
      - bluebird
    image: turinginst/twitcher:v0.10.15-3-g1cf28bb
    command: http-server .
    ports:
      - "8080:8080"
