# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: nats

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pyqt
  - numpy
  - scipy
  - matplotlib
  - pandas
  - r-base

  - pip:
    - flask
    - flask_cors
    - flask_restful
    - markdown
    - msgpack
    - python-dotenv
    - pyzmq
    - pygame
    - pyproj    # birdhouse dep
    - pyqtwebengine
    - pyopengl
    - pyopengl-accelerate
    - psutil==5.5.*
    - pytest==4.1.*
    - pylint==2.2.*
    - pylint-exit==1.0.*
    - pyqt5
    - ruamel_yaml
